In [80]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## Setup and Imports

In [81]:
import pandas as pd
import numpy as np
from numpy.linalg import norm

In [82]:
OHCO = ['doc_title', 'para_num', 'sentence_num', 'token_num']
bags = dict(
    SENTS = OHCO[:3],
    PARAS = OHCO[:2],
    STORIES = OHCO[:1]
)
bag = 'PARAS' # Orginally stories but swtiched to paragraphs for later topic modeling

In [83]:
OHCO[:1]

['doc_title']

In [84]:
VOCAB = pd.read_csv('data/pg2591-VOCAB.csv')
VOCAB.set_index('term_str',inplace=True)
VOCAB.head()

             n         p         i  n_chars max_pos_group max_pos p_stem  stop
term_str
the       6927  0.068553  3.866638        3            DT      DT    the     1
and       5433  0.053768  4.217119        3            CC      CC    and     1
to        2662  0.026344  5.246358        2            TO      TO     to     1
he        2093  0.020713  5.593296        2            PR     PRP     he     1
a         1909  0.018892  5.726051        1            DT      DT      a     1

In [85]:
TOKENS = pd.read_csv("data/p2591-TOKENS.csv").set_index(OHCO).dropna()
TOKENS=TOKENS.reset_index()
TOKENS.head()

,doc_title,para_num,sentence_num,token_num,pos_tuple,pos,token_str,term_str,pos_group
0,ASHPUTTEL,0,0,0,"('The', 'DT')",DT,The,the,DT
1,ASHPUTTEL,0,0,1,"('wife', 'NN')",NN,wife,wife,NN
2,ASHPUTTEL,0,0,2,"('of', 'IN')",IN,of,of,IN
3,ASHPUTTEL,0,0,3,"('a', 'DT')",DT,a,a,DT
4,ASHPUTTEL,0,0,4,"('rich', 'JJ')",JJ,rich,rich,JJ

## BOW by STORIES

In [86]:
BOW = TOKENS.groupby(bags[bag]+['term_str']).term_str.count().to_frame('n') 
BOW

                               n
doc_title para_num term_str
ASHPUTTEL 0        a           4
                   about       1
                   afterwards  1
                   again       1
                   all         1
...                           ..
TOM THUMB 21       traveller   1
                   very        1
                   was         2
                   whole       1
                   with        1

[59644 rows x 1 columns]

## DTCM Table

In [87]:
DTCM = BOW.n.unstack(fill_value=0)
DTCM.head(10)

term_str            1  2  3  _jug  _my_  a  abashed  abide  able  abode  ...  \
doc_title para_num                                                       ...
ASHPUTTEL 0         0  0  0     0     0  4        0      0     0      0  ...
          1         0  0  0     0     0  0        0      0     0      0  ...
          2         0  0  0     0     0  4        0      0     0      0  ...
          3         0  0  0     0     0  2        0      0     0      0  ...
          4         0  0  0     0     0  0        0      0     0      0  ...
          5         0  0  0     0     0  0        0      0     0      0  ...
          6         0  0  0     0     0  1        0      0     0      0  ...
          7         0  0  0     0     0  0        0      0     0      0  ...
          8         0  0  0     0     0  0        0      0     0      0  ...
          9         0  0  0     0     0  0        0      0     0      0  ...

term_str            yonder  you  young  younger  youngest  your  yours  \
doc_title para_num
ASHPUTTEL 0              0    1      0        0         0     0      0
          1              0    0      0        0         0     0      0
          2              0    2      0        0         0     2      0
          3              0    5      0        0         0     0      0
          4              0    0      0        0         0     0      0
          5              0    0      0        0         0     0      0
          6              0    0      0        0         0     0      0
          7              0    5      0        0         0     0      0
          8              0    0      0        0         0     0      0
          9              0    0      0        0         0     0      0

term_str            yourself  yourselves  youth
doc_title para_num
ASHPUTTEL 0                0           0      0
          1                0           0      0
          2                0           0      0
          3                0           0      0
          4                0           0      0
          5                0           0      0
          6                0           0      0
          7                0           0      0
          8                0           0      0
          9                0           0      0

[10 rows x 4804 columns]

## Making TFIDF

In [88]:
tf_method = 'sum'         # sum, max, log, double_norm, raw, binary
tf_norm_k = .5            # only used for double_norm
idf_method = 'standard'   # standard, max, smooth
gradient_cmap = 'YlGnBu'  # YlGn, GnBu, YlGnBu; For tables; see https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html

In [89]:
print('TF method:', tf_method)

if tf_method == 'sum':
    TF = DTCM.T / DTCM.T.sum()

elif tf_method == 'max':
    TF = DTCM.T / DTCM.T.max()
    
elif tf_method == 'log':
    TF = np.log2(1 + DTCM.T)
    
elif tf_method == 'raw':
    TF = DTCM.T
    
elif tf_method == 'double_norm':
    TF = DTCM.T / DTCM.T.max()
    
elif tf_method == 'binary':
    TF = DTCM.T.astype('bool').astype('int')
    
TF = TF.T

TF method: sum

In [90]:
TF.head(10)

term_str              1    2    3  _jug  _my_         a  abashed  abide  able  \
doc_title para_num
ASHPUTTEL 0         0.0  0.0  0.0   0.0   0.0  0.020101      0.0    0.0   0.0
          1         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0
          2         0.0  0.0  0.0   0.0   0.0  0.020000      0.0    0.0   0.0
          3         0.0  0.0  0.0   0.0   0.0  0.010363      0.0    0.0   0.0
          4         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0
          5         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0
          6         0.0  0.0  0.0   0.0   0.0  0.009709      0.0    0.0   0.0
          7         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0
          8         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0
          9         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0

term_str            abode  ...  yonder       you  young  younger  youngest  \
doc_title para_num         ...
ASHPUTTEL 0           0.0  ...     0.0  0.005025    0.0      0.0       0.0
          1           0.0  ...     0.0  0.000000    0.0      0.0       0.0
          2           0.0  ...     0.0  0.010000    0.0      0.0       0.0
          3           0.0  ...     0.0  0.025907    0.0      0.0       0.0
          4           0.0  ...     0.0  0.000000    0.0      0.0       0.0
          5           0.0  ...     0.0  0.000000    0.0      0.0       0.0
          6           0.0  ...     0.0  0.000000    0.0      0.0       0.0
          7           0.0  ...     0.0  0.052632    0.0      0.0       0.0
          8           0.0  ...     0.0  0.000000    0.0      0.0       0.0
          9           0.0  ...     0.0  0.000000    0.0      0.0       0.0

term_str            your  yours  yourself  yourselves  youth
doc_title para_num
ASHPUTTEL 0         0.00    0.0       0.0         0.0    0.0
          1         0.00    0.0       0.0         0.0    0.0
          2         0.01    0.0       0.0         0.0    0.0
          3         0.00    0.0       0.0         0.0    0.0
          4         0.00    0.0       0.0         0.0    0.0
          5         0.00    0.0       0.0         0.0    0.0
          6         0.00    0.0       0.0         0.0    0.0
          7         0.00    0.0       0.0         0.0    0.0
          8         0.00    0.0       0.0         0.0    0.0
          9         0.00    0.0       0.0         0.0    0.0

[10 rows x 4804 columns]

In [91]:
DTCM.astype(bool)

term_str                1      2      3   _jug   _my_      a  abashed  abide  \
doc_title para_num
ASHPUTTEL 0         False  False  False  False  False   True    False  False
          1         False  False  False  False  False  False    False  False
          2         False  False  False  False  False   True    False  False
          3         False  False  False  False  False   True    False  False
          4         False  False  False  False  False  False    False  False
...                   ...    ...    ...    ...    ...    ...      ...    ...
TOM THUMB 17        False  False  False  False  False  False    False  False
          18        False  False  False  False  False   True    False  False
          19        False  False  False  False  False   True    False  False
          20        False  False  False  False  False  False    False  False
          21        False  False  False  False  False   True    False  False

term_str             able  abode  ...  yonder    you  young  younger  \
doc_title para_num                ...
ASHPUTTEL 0         False  False  ...   False   True  False    False
          1         False  False  ...   False  False  False    False
          2         False  False  ...   False   True  False    False
          3         False  False  ...   False   True  False    False
          4         False  False  ...   False  False  False    False
...                   ...    ...  ...     ...    ...    ...      ...
TOM THUMB 17        False  False  ...   False  False  False    False
          18        False  False  ...   False   True  False    False
          19        False  False  ...   False   True  False    False
          20        False  False  ...   False   True  False    False
          21        False  False  ...   False  False  False    False

term_str            youngest   your  yours  yourself  yourselves  youth
doc_title para_num
ASHPUTTEL 0            False  False  False     False       False  False
          1            False  False  False     False       False  False
          2            False   True  False     False       False  False
          3            False  False  False     False       False  False
          4            False  False  False     False       False  False
...                      ...    ...    ...       ...         ...    ...
TOM THUMB 17           False  False  False     False       False  False
          18           False   True  False     False       False  False
          19           False  False  False     False       False  False
          20           False  False  False     False       False  False
          21           False  False  False     False       False  False

[906 rows x 4804 columns]

In [92]:
DF = DTCM.astype('bool').sum() 
DF

term_str
1               1
2               1
3               1
_jug            1
_my_            1
             ...
your          153
yours           3
yourself       28
yourselves      4
youth          19
Length: 4804, dtype: int64

In [93]:
N = DTCM.shape[0]

N

906

In [94]:
print('IDF method:', idf_method)

if idf_method == 'standard':
    IDF = np.log2(N / DF)

elif idf_method == 'max':
    IDF = np.log2(DF.max() / DF) 

elif idf_method == 'plus':
    IDF = np.log2(N / DF) + 1

# This is what SciKit Learn uses
elif idf_method == 'smooth':
    IDF = np.log2((1 + N) / (1 + DF)) + 1

IDF method: standard

In [95]:
TFIDF = TF * IDF
TFIDF.head()

term_str              1    2    3  _jug  _my_         a  abashed  abide  able  \
doc_title para_num
ASHPUTTEL 0         0.0  0.0  0.0   0.0   0.0  0.012291      0.0    0.0   0.0
          1         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0
          2         0.0  0.0  0.0   0.0   0.0  0.012230      0.0    0.0   0.0
          3         0.0  0.0  0.0   0.0   0.0  0.006337      0.0    0.0   0.0
          4         0.0  0.0  0.0   0.0   0.0  0.000000      0.0    0.0   0.0

term_str            abode  ...  yonder       you  young  younger  youngest  \
doc_title para_num         ...
ASHPUTTEL 0           0.0  ...     0.0  0.006875    0.0      0.0       0.0
          1           0.0  ...     0.0  0.000000    0.0      0.0       0.0
          2           0.0  ...     0.0  0.013680    0.0      0.0       0.0
          3           0.0  ...     0.0  0.035441    0.0      0.0       0.0
          4           0.0  ...     0.0  0.000000    0.0      0.0       0.0

term_str               your  yours  yourself  yourselves  youth
doc_title para_num
ASHPUTTEL 0         0.00000    0.0       0.0         0.0    0.0
          1         0.00000    0.0       0.0         0.0    0.0
          2         0.02566    0.0       0.0         0.0    0.0
          3         0.00000    0.0       0.0         0.0    0.0
          4         0.00000    0.0       0.0         0.0    0.0

[5 rows x 4804 columns]

In [96]:
DF.index

Index(['1', '2', '3', '_jug', '_my_', 'a', 'abashed', 'abide', 'able', 'abode',
       ...
       'yonder', 'you', 'young', 'younger', 'youngest', 'your', 'yours',
       'yourself', 'yourselves', 'youth'],
      dtype='object', name='term_str', length=4804)

In [97]:
VOCAB.index

Index(['the', 'and', 'to', 'he', 'a', 'was', 'of', 'it', 'she', 'you',
       ...
       'clap', 'mount', 'removed', 'fattening', 'stops', 'bath',
       'bathinghouse', 'arrive', 'impatience', 'fears'],
      dtype='object', name='term_str', length=4804)

In [98]:
VOCAB['df'] = DF
VOCAB['idf'] = IDF
VOCAB['tfidf_mean'] = TFIDF.mean()

## Making Normalized Reduced TFIDF

In [99]:
N = TOKENS.reset_index().value_counts(['doc_title']).shape[0]

VOCAB['tfidf_mean'] = TFIDF.mean() 
VOCAB['dfidf'] = VOCAB.df * VOCAB.idf # DFIDF is the same as mean boolean TFIDF
VOCAB['dp'] = VOCAB.df / N
VOCAB['di'] = np.log2(1/VOCAB.dp)
VOCAB['dh'] = VOCAB.dp * VOCAB.di
VOCAB

,n,p,i,n_chars,max_pos_group,max_pos,p_stem,stop,df,idf,tfidf_mean,dfidf,dp,di,dh
term_str,,,,,,,,,,,,,,,
the,6927,0.068553,3.866638,3,DT,DT,the,1,801,0.177709,0.012154,142.344755,12.919355,-3.691462,-47.691309
and,5433,0.053768,4.217119,3,CC,CC,and,1,787,0.203147,0.010771,159.877015,12.693548,-3.666024,-46.534847
to,2662,0.026344,5.246358,2,TO,TO,to,1,677,0.420355,0.010749,284.580482,10.919355,-3.448816,-37.658843
he,2093,0.020713,5.593296,2,PR,PRP,he,1,499,0.860471,0.015444,429.375146,8.048387,-3.008700,-24.215180
a,1909,0.018892,5.726051,1,DT,DT,a,1,593,0.611479,0.010418,362.607015,9.564516,-3.257692,-31.158248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
bath,1,0.000010,16.624653,4,NN,NN,bath,0,1,9.823367,0.000113,9.823367,0.016129,5.954196,0.096035
bathinghouse,1,0.000010,16.624653,12,NN,NN,bathinghous,0,1,9.823367,0.000087,9.823367,0.016129,5.954196,0.096035
arrive,1,0.000010,16.624653,6,VB,VB,arriv,0,1,9.823367,0.000087,9.823367,0.016129,5.954196,0.096035
impatience,1,0.000010,16.624653,10,NN,NN,impati,0,1,9.823367,0.000055,9.823367,0.016129,5.954196,0.096035
fears,1,0.000010,16.624653,5,VB,VBZ,fear,0,1,9.823367,0.000046,9.823367,0.016129,5.954196,0.096035

In [100]:
thresh = VOCAB.dh.quantile(.8).round(3) # Lowered threshold because i was getting such little results
float(thresh)

0.326

In [101]:
SIGS = VOCAB[VOCAB.dh >= thresh]
SIGS[['max_pos', 'n', 'i', 'dh']].sort_values('dh', ascending=False)\
    .head(25).style.background_gradient(cmap='YlGnBu')

In [102]:
TFIDF_SIGS = TFIDF[SIGS.index].copy()
TFIDF_SIGS

term_str            hans  gretel  fox  children      wolf      fire  boy  cat  \
doc_title para_num
ASHPUTTEL 0          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          1          0.0     0.0  0.0       0.0  0.000000  0.052823  0.0  0.0
          2          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          3          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          4          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
...                  ...     ...  ...       ...       ...       ...  ...  ...
TOM THUMB 17         0.0     0.0  0.0       0.0  0.066375  0.000000  0.0  0.0
          18         0.0     0.0  0.0       0.0  0.061269  0.000000  0.0  0.0
          19         0.0     0.0  0.0       0.0  0.081000  0.000000  0.0  0.0
          20         0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          21         0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0

term_str            tailor  prince  ...  shade  mighty  least  sides  devour  \
doc_title para_num                  ...
ASHPUTTEL 0            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          1            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          2            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          3            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          4            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
...                    ...     ...  ...    ...     ...    ...    ...     ...
TOM THUMB 17           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          18           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          19           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          20           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          21           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0

term_str            searched  started  meant  hide  comrade
doc_title para_num
ASHPUTTEL 0              0.0      0.0    0.0   0.0      0.0
          1              0.0      0.0    0.0   0.0      0.0
          2              0.0      0.0    0.0   0.0      0.0
          3              0.0      0.0    0.0   0.0      0.0
          4              0.0      0.0    0.0   0.0      0.0
...                      ...      ...    ...   ...      ...
TOM THUMB 17             0.0      0.0    0.0   0.0      0.0
          18             0.0      0.0    0.0   0.0      0.0
          19             0.0      0.0    0.0   0.0      0.0
          20             0.0      0.0    0.0   0.0      0.0
          21             0.0      0.0    0.0   0.0      0.0

[906 rows x 1065 columns]

### Normalizing Reduced Table

In [103]:
L2 = TFIDF_SIGS.apply(lambda x: x / norm(x), 1) # Pythagorean, AKA Euclidean
L2

term_str            hans  gretel  fox  children      wolf      fire  boy  cat  \
doc_title para_num
ASHPUTTEL 0          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          1          0.0     0.0  0.0       0.0  0.000000  0.171935  0.0  0.0
          2          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          3          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          4          0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
...                  ...     ...  ...       ...       ...       ...  ...  ...
TOM THUMB 17         0.0     0.0  0.0       0.0  0.322748  0.000000  0.0  0.0
          18         0.0     0.0  0.0       0.0  0.264092  0.000000  0.0  0.0
          19         0.0     0.0  0.0       0.0  0.431042  0.000000  0.0  0.0
          20         0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0
          21         0.0     0.0  0.0       0.0  0.000000  0.000000  0.0  0.0

term_str            tailor  prince  ...  shade  mighty  least  sides  devour  \
doc_title para_num                  ...
ASHPUTTEL 0            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          1            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          2            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          3            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          4            0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
...                    ...     ...  ...    ...     ...    ...    ...     ...
TOM THUMB 17           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          18           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          19           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          20           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0
          21           0.0     0.0  ...    0.0     0.0    0.0    0.0     0.0

term_str            searched  started  meant  hide  comrade
doc_title para_num
ASHPUTTEL 0              0.0      0.0    0.0   0.0      0.0
          1              0.0      0.0    0.0   0.0      0.0
          2              0.0      0.0    0.0   0.0      0.0
          3              0.0      0.0    0.0   0.0      0.0
          4              0.0      0.0    0.0   0.0      0.0
...                      ...      ...    ...   ...      ...
TOM THUMB 17             0.0      0.0    0.0   0.0      0.0
          18             0.0      0.0    0.0   0.0      0.0
          19             0.0      0.0    0.0   0.0      0.0
          20             0.0      0.0    0.0   0.0      0.0
          21             0.0      0.0    0.0   0.0      0.0

[906 rows x 1065 columns]

## Save Reduced and Normlaizd TFIDF table

In [104]:
output_dir ="data"

In [105]:
L2.to_csv(f"{output_dir}/pg2591-TFIDF_Reduced.csv", index=True)

In [106]:
DTCM.to_csv(f"{output_dir}/pg2591-DTM.csv", index=True)