# Topic Modeling with LDA

Did chunking in hopes of getting better topic models

## Setup and Imports

In [242]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation as LDA, NMF 

from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [243]:
sns.set_theme(style="white")
colors = "YlGnBu"

In [244]:
model_type = 'lda' # or 'nmf'
data_home = "../input"

In [245]:
import os

output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

In [246]:
OHCO = ['doc_title', 'chunk_id','token_id']
CHUNKS = OHCO[:2]
STORIES = OHCO[:1]

BAG = CHUNKS

In [247]:
LIB = pd.read_csv('data/pg2591-LIB.csv',)
LIB.set_index('doc_title', inplace=True)
LIB.head()

                          volume
doc_title
THE GOLDEN BIRD                1
HANS IN LUCK                   1
JORINDA AND JORINDEL           1
THE TRAVELLING MUSICIANS       1
OLD SULTAN                     1

In [248]:
TOKENS = pd.read_csv('data/chunked_tokens.csv').set_index(OHCO).dropna()
TOKENS

                                   pos_tuple  pos token_str term_str pos_group
doc_title chunk_id token_id
ASHPUTTEL 0        0           ('the', 'DT')   DT       the      the        DT
                   1          ('wife', 'NN')   NN      wife     wife        NN
                   2            ('of', 'IN')   IN        of       of        IN
                   3             ('a', 'DT')   DT         a        a        DT
                   4          ('rich', 'JJ')   JJ      rich     rich        JJ
...                                      ...  ...       ...      ...       ...
TOM THUMB 19       66           ('s', 'VBZ')  VBZ         s        s        VB
                   67           ('no', 'DT')   DT        no       no        DT
                   68        ('place', 'NN')   NN     place    place        NN
                   69         ('like', 'IN')   IN      like     like        IN
                   70         ('home', 'NN')   NN      home     home        NN

[115213 rows x 5 columns]

In [249]:
DOCS = TOKENS[TOKENS.pos.str.match(r'^NNS?$')]\
    .groupby(BAG).term_str\
    .apply(lambda x: ' '.join(map(str,x)))\
    .to_frame()\
    .rename(columns={'term_str':'doc_str'})

DOCS

                                                              doc_str
doc_title chunk_id
ASHPUTTEL 0         wife man end drew daughter bedside girl i watc...
          1         fair face foul heart sorry time girl goodforno...
          2         hearth ashes course dirty ashputtel father wif...
          3         daughter mother s grave tears tree times day b...
          4         hair shoes sashes king s feast ball mother not...
...                                                               ...
TOM THUMB 15        wolf chat friend i treat s wolf house father s...
          16        content way tom shout noise wolf everybody hou...
          17        wolf woodman axe wife scythe do woodman i head...
          18        ah father world i way home air father i mouseh...
          19        clothes ones journey home father mother peace ...

[784 rows x 1 columns]

## Create Vector Space

In [250]:
from sklearn.feature_extraction import text

my_stop_words = list(text.ENGLISH_STOP_WORDS.union(['yes']))
my_stop_words[:10]
# my_stop_words.append('said') # add more words to stop words because they appeared it most topics and ruined the topics
# my_stop_words.append('came')
# my_stop_words.append('went')

['nothing',
 'put',
 'himself',
 'otherwise',
 'these',
 'in',
 'between',
 'except',
 'will',
 'how']

In [251]:
count_engine = CountVectorizer(max_df=.75, min_df=5, stop_words=my_stop_words) # Got some advice from clause to lower min ax max df because corpus ins amll
count_model = count_engine.fit_transform(DOCS.doc_str)
TERMS = count_engine.get_feature_names_out()
VOCAB = pd.DataFrame(index=TERMS)
VOCAB.index.name = 'term_str'
DTM_chunk = pd.DataFrame(count_model.toarray(), index=DOCS.index, columns=TERMS)
DTM_chunk

                    account  advice  ah  air  alas  ale  anger  animals  \
doc_title chunk_id
ASHPUTTEL 0               0       0   0    0     0    0      0        0
          1               0       0   0    0     0    0      0        0
          2               0       0   0    0     0    0      0        0
          3               0       0   0    0     0    0      0        0
          4               0       0   0    0     0    0      0        0
...                     ...     ...  ..  ...   ...  ...    ...      ...
TOM THUMB 15              0       0   0    0     0    0      0        0
          16              0       0   0    0     0    0      0        0
          17              0       0   1    0     0    0      0        0
          18              0       0   1    1     0    0      0        0
          19              0       0   0    0     0    0      0        0

                    answer  apple  ...  woods  word  words  work  world  \
doc_title chunk_id                 ...
ASHPUTTEL 0              0      0  ...      0     0      0     0      0
          1              0      0  ...      0     0      0     1      0
          2              0      0  ...      0     0      0     0      0
          3              0      0  ...      0     0      0     0      0
          4              0      0  ...      0     0      0     0      0
...                    ...    ...  ...    ...   ...    ...   ...    ...
TOM THUMB 15             0      0  ...      0     0      0     0      0
          16             0      0  ...      0     0      0     0      0
          17             0      0  ...      0     0      0     0      0
          18             0      0  ...      0     0      0     0      2
          19             0      0  ...      0     0      0     0      0

                    wretch  yard  year  years  youth
doc_title chunk_id
ASHPUTTEL 0              0     0     0      0      0
          1              0     0     0      0      0
          2              0     0     0      0      0
          3              0     0     0      0      0
          4              0     0     0      0      0
...                    ...   ...   ...    ...    ...
TOM THUMB 15             0     0     0      0      0
          16             0     0     0      0      0
          17             0     0     0      0      0
          18             0     0     0      0      0
          19             0     0     0      0      0

[784 rows x 707 columns]

In [252]:
# Used claude code to help with tfidf engine and model because I want nmf to get better topics than lda
# tfidf_engine = TfidfVectorizer(max_df=.75, min_df=5, stop_words=my_stop_words)
# tfidf_model = tfidf_engine.fit_transform(DOCS.doc_str)
# TERMS = tfidf_engine.get_feature_names_out()
# TFIDF = tfidf_engine.fit_transform(DOCS.doc_str)
# VOCAB = pd.DataFrame(index=TERMS)
# VOCAB.index.name = 'term_str'
# DTM = pd.DataFrame(tfidf_model.toarray(), index=DOCS.index, columns=TERMS)
# DTM

## Generate Model with 20 Topics

In [253]:
n_topics = 5
max_iter = 100
n_top_terms = 5
TNAMES = [f"T{str(x).zfill(len(str(n_topics)))}" for x in range(n_topics)]

In [254]:
if model_type == 'lda':
    topic_engine = LDA(n_components=n_topics, max_iter=max_iter)
elif model_type == 'nmf':
    topic_engine = NMF(n_components=n_topics, max_iter=max_iter)
topic_model = topic_engine.fit_transform(count_model)

In [255]:
model_type

'lda'

## THETA

In [256]:
THETA = pd.DataFrame(topic_model, index=DOCS.index, columns=TNAMES)
THETA.columns.name = 'topic_id'
THETA.sample(10).T.style.background_gradient(cmap=colors, axis=None)

In [257]:
THETA_vol=THETA.join(LIB)

THETA_vol_agg=THETA_vol.groupby('volume').mean()
top_volume=THETA_vol_agg.idxmax()
# topic_ideas = {
#     'T0':'T0: matriarchy/domesticity',
#     'T1': 'T1: patriarchy/family',
#     'T2': 'T2: outdoors',
#     'T3': 'T3:family/time',
#     'T4': 'T4: princess tales'
# }
# THETA_vol.rename(columns=topic_ideas, inplace=True)
THETA_vol_agg.style.background_gradient(cmap=colors, axis=None)

## PHI

In [258]:
PHI = pd.DataFrame(topic_engine.components_, columns=TERMS, index=TNAMES)
PHI.index.name = 'topic_id'
PHI.columns.name = 'term_str'
PHI.T.sample(10).T.style.background_gradient(cmap=colors, axis=None)

## Get Top Terms By Topic

In [ ]:
TOPICS = PHI.stack().groupby('topic_id')\
    .apply(lambda x: ' '.join(x.sort_values(ascending=False).head(n_top_terms).reset_index().term_str))\
    .to_frame('top_terms')
TOPICS

NameError: name 'seed' is not defined

## PCA + LDA

In [ ]:
THETA_vol

                          T0        T1        T2        T3        T4  volume
doc_title chunk_id
ASHPUTTEL 0         0.305052  0.008476  0.008588  0.283725  0.394160       1
          1         0.009398  0.009252  0.009216  0.962807  0.009327       1
          2         0.967255  0.008127  0.008103  0.008242  0.008274       1
          3         0.245894  0.011249  0.153755  0.011269  0.577833       1
          4         0.325502  0.016821  0.016714  0.375178  0.265786       1
...                      ...       ...       ...       ...       ...     ...
TOM THUMB 15        0.011334  0.519635  0.446503  0.011204  0.011324       1
          16        0.013559  0.356057  0.603409  0.013494  0.013481       1
          17        0.009738  0.428655  0.542002  0.009921  0.009684       1
          18        0.012739  0.404628  0.012890  0.012802  0.556941       1
          19        0.017125  0.016909  0.017003  0.016824  0.932138       1

[784 rows x 6 columns]

In [ ]:
THETA.join(LIB)

                          T0        T1        T2        T3        T4  volume
doc_title chunk_id
ASHPUTTEL 0         0.305052  0.008476  0.008588  0.283725  0.394160       1
          1         0.009398  0.009252  0.009216  0.962807  0.009327       1
          2         0.967255  0.008127  0.008103  0.008242  0.008274       1
          3         0.245894  0.011249  0.153755  0.011269  0.577833       1
          4         0.325502  0.016821  0.016714  0.375178  0.265786       1
...                      ...       ...       ...       ...       ...     ...
TOM THUMB 15        0.011334  0.519635  0.446503  0.011204  0.011324       1
          16        0.013559  0.356057  0.603409  0.013494  0.013481       1
          17        0.009738  0.428655  0.542002  0.009921  0.009684       1
          18        0.012739  0.404628  0.012890  0.012802  0.556941       1
          19        0.017125  0.016909  0.017003  0.016824  0.932138       1

[784 rows x 6 columns]

In [ ]:
pca_engine = PCA(n_components=4)
TCM = pd.DataFrame(pca_engine.fit_transform(THETA.T),index=THETA.T.index)
TCM.columns = ['PC{}'.format(i) for i in TCM.columns]
TCM['doc_mean_weight']= TCM.mean(axis=1)
TCM['top_volume'] = top_volume
TCM.style.background_gradient(cmap=colors, axis=None)

In [ ]:
def vis_pcs(a, b,DCM,):
    fig =px.scatter(DCM, 
        f"PC{a}", f"PC{b}", 
        color=DCM['top_volume'].astype('category'), 
        size= np.abs(DCM['doc_mean_weight']),
        # hover_name=DCM.title_para,
        marginal_x='box', 
        height=1000, 
        width=1200)
    return fig

In [ ]:
vis_pcs(1,2,TCM)

## Save Files to Output

In [ ]:
THETA.to_csv(f"{output_dir}/pg2591-THETA.csv", index=True)
PHI.to_csv(f"{output_dir}/pg2591-PHI.csv", index=True)
DTM_chunk.to_csv(f"{output_dir}/pg2591-CHUNKED_DTM.csv", index=True)
TOPICS.to_csv(f"{output_dir}/pg2591-TOPICS.csv", index=True)